# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e6a42eede98a76c85281c4d5aca057216ce402e9d65408d654164d92f816762f23c813b8745c887095c94d8455136d3d2aeedb751a0e27f70ab89ff2f2f6be2

test:
  secret_key_base: e1ddac6081caa70b6df4f497b514d37884adb1a0f7eb5b010d9601b0bd88ce7c0156cbb9057a08e422fc8b0bee2ba480c4b4a7670b5cee4dd9da2f16bf95301c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
